# -*- coding: utf-8 -*-
"""feature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ek_DuHX5RYQyaQKVyt9hcAAfMRZUJta
"""

import librosa
import numpy as np
import pandas as pd

def extract_librosa_features(audio_file_path):
    """
    Extracts a set of robust audio features using the Librosa library.
    """
    try:
        # Load the audio file
        y, sr = librosa.load(audio_file_path, sr=None)

        # Extract features
        mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
        chroma = librosa.feature.chroma_stft(y=y, sr=sr)
        mel = librosa.feature.melspectrogram(y=y, sr=sr)
        contrast = librosa.feature.spectral_contrast(y=y, sr=sr)
        tonnetz = librosa.feature.tonnetz(y=librosa.effects.harmonic(y), sr=sr)

        # Aggregate features - we use the mean of each feature across the audio file
        features = {
            'mfcc1_mean': np.mean(mfccs[0]), 'mfcc2_mean': np.mean(mfccs[1]),
            'mfcc3_mean': np.mean(mfccs[2]), 'mfcc4_mean': np.mean(mfccs[3]),
            'mfcc5_mean': np.mean(mfccs[4]), 'mfcc6_mean': np.mean(mfccs[5]),
            'mfcc7_mean': np.mean(mfccs[6]), 'mfcc8_mean': np.mean(mfccs[7]),
            'mfcc9_mean': np.mean(mfccs[8]), 'mfcc10_mean': np.mean(mfccs[9]),
            'mfcc11_mean': np.mean(mfccs[10]),'mfcc12_mean': np.mean(mfccs[11]),
            'mfcc13_mean': np.mean(mfccs[12]),
            'chroma_mean': np.mean(chroma),
            'mel_mean': np.mean(mel),
            'contrast_mean': np.mean(contrast),
            'tonnetz_mean': np.mean(tonnetz),
            'zero_crossing_rate_mean': np.mean(librosa.feature.zero_crossing_rate(y)),
            'spectral_centroid_mean': np.mean(librosa.feature.spectral_centroid(y=y, sr=sr)),
            'spectral_rolloff_mean': np.mean(librosa.feature.spectral_rolloff(y=y, sr=sr)),
        }

        return pd.DataFrame(features, index=[0])

    except Exception as e:
        print(f"Error processing audio file with Librosa: {e}")
        return None